### ISSUE TITLE
return_local: some returns list, some array

### ISSUE THREAD

**Issue by WandrilleD** [hj-n/zadu#7]
In return_local mode, some of the metrics return arrays (eg, trustworthiness_continuity), whereas other return lists (eg steadiness_cohesiveness).
Ensuring that these have the same interface would be helpful to integrate ZADU to our data exploration pipelines.
I would personally advocate for returning all arrays.
Thanks

**Comment by hj-n** [comment]
We revised the code to always return numpy array
Thank you for the report

Please check commit [43716d2](https://github.com/hj-n/zadu/commit/43716d2b56799f87d3dc679778204ca84d34fff3)
